name: autofix.ci

on:
  pull_request:
  push:

permissions: {}

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: |
          bun i
          bun prettier . --write
      - uses: autofix-ci/action@v1
        with:
          commit-message: 'Apply Prettier format'
